### ISSUE TITLE
"Copy" button is not working on OAuth page

### ISSUE THREAD

**Issue by ghost** [fedibird/mastodon#10]
### Expected behaviour

The token should be copied to clipboard.

### Actual behaviour

The token is not copied to clipboard when the button is clicked.

### Steps to reproduce the problem

Connect a 3rd party client
![Screenshot](https://user-images.githubusercontent.com/121358169/209449897-c1172c6a-c119-44df-80c0-f78b3dac59c5.png)

### Specifications

fedibird.com prod
e088eef4011f76d9dc0bb20f6bf3a3fa3cd8cd3d

**Comment by noellabo** [comment]
Thanks for the report, I wasn't able to handle the case where initial_state didn't exist.

Fixed in the current latest commit
https://github.com/fedibird/mastodon/commit/e1ed88763cdcdde335ff1084468957ec4c22e3b5
