### ISSUE TITLE
サードパーティアプリからフォローリクエスト(api/v1/follow_requests)を取得することができない

### ISSUE THREAD

**Issue by pantasystem** [fedibird/mastodon#11]
### Expected behaviour

サードパーティアプリからフォローリクエストを取得することができる

### Actual behaviour

scopesがread writeのTokenでapi/v1/follow_requestsにGETリクエストを送信すると403が返ってきてしまう

### Steps to reproduce the problem

1. scopesがread writeのアクセストークンを生成する
2. そのTokenをAuthorizationヘッダーにBearer Tokenとして指定してapi/v1/follow_requestsにリクエストを送信する
3. 403エラーと共に下記のレスポンスが返ってくる

```
{
  "error": "This action is outside the authorized scopes"
}
```
また他のインスタンス(mstdn.jpやmastodon.social)などで同様の方法で検証したところ
正常に返ってきたのでアクセストークンの生成方法やscopesの指定に問題はないと考えられます。

### Specifications

version 0.1

**Comment by noellabo** [comment]
あー、v3.5から仕様が変わってますね。追従しちゃいましょう。
https://github.com/mastodon/mastodon/pull/17678

**Comment by noellabo** [comment]
クライアントアプリとしては、

- バージョン判別してscopeを変える
- 古いfollow scopeで互換性を優先する
- v3.4.1以前は該当APIを非対応とする

のいずれかの対応になるかと思います。

**Comment by noellabo** [comment]
Fix https://github.com/fedibird/mastodon/commit/5174b4619032e1df2faa105425d13e4dd24ee29d

**Comment by pantasystem** [comment]
なるほどv3.5で仕様が変わったのですね
教えていただきありがとうございます。
無事に解決することができそうです。
ご対応ありがとうございました。
