### ISSUE TITLE
Threadsとの接続ができない

### ISSUE THREAD

**Issue by hanubeki** [fedibird/mastodon#19]
### Expected behaviour

Threadsのアカウントを検索・フォローできる

### Actual behaviour

検索欄で `@hanubeki@threads.net` を検索しても該当のアカウントがマッチしない

### Steps to reproduce the problem

既知の問題かと思われますが一応こちらにも。

1. Threadsにてフェディバースでのシェア (ベータ) をオンにする
2. 1.でオンにしたアカウント `@hanubeki@threads.net` を検索ボックスに入力する
3. 該当するアカウントが見つからない

追伸: Threadsにて `threads.net` のバッジがついているアカウントのみがFediverseでフォロー可能になるようです。

### Specifications

Microsoft Edge 122 on Windows 11 23H2

**Comment by hanubeki** [comment]
Threadsがフェディバースの他のサーバーとの通信をブロックするケースについて
https://help.instagram.com/914046486923176

> Metaは、次のいずれかを欠いている場合もサーバーもブロックします。
（中略）
> * 一般にアクセスできるフィード

LTLのないFedibirdがこれに抵触しているのではないかという話が出ています。
（だとするとnightlyが繋がっているらしいというのが謎ですが…）

**Comment by noellabo** [comment]
非ログイン時に連合またはローカルタイムラインを参照するページがうまく動いていない不具合があるのを確認しました。こちらは解決を図ります。
https://fedibird.com/public
https://nightly.fedibird.com/public

さて、Threadsにつながらない問題ですが、WebfingerによりThreadsの対象アカウントのuriを取得したあと（これは問題なく動く）、そのuriに対する署名付きリクエストに429ステータスが返ってくるというのが具体的な挙動です。

意図的なブロックによるものかについては、慎重に確認をとりたいと思います。

**Comment by noellabo** [comment]
- fedibird.comとnightly.fedibird.comはほぼ同一のソースコードで動いていますが、nightlyはつながります
  - Mastodonのバージョンによる非互換や足切りではないようです
  - Mastodonのソースリポジトリによる改造の有無をみているわけではないようです
- fedibird.comと同一のサーバ上に立てた実験サーバからはつながります
  - IPアドレスベースの制限ではなさそうです
  - IPアドレスからの逆引きはfedibird.comになるので、逆引きしたドメインは見ていないと思います
  - 署名付きリクエストが必須なので、署名したアカウントのドメインをみているかもしれません

**Comment by noellabo** [comment]
- Instagramをスクレイピングしようとするとスロットリングで429 Too Many Accessになることが知られている
- fedibird.comからInstagramのプレビューカードがみられない（取得に失敗する）ことが多い
- nightly.fedibird.comからInstagramのプレビューカードを取得するのはエラーにならず、基本的に問題無い
- （YouTubeリンクもInstagram同様にfedibird.comだけ埋め込みが取得できないことが度々起こる）
- ThreadsのインフラはInstagramを下地にしている

ということで、大量アクセスを弾く仕組みに引っかかって、本当に429を返すフラグ状態になっていることも考えられます。

**Comment by hanubeki** [comment]
2024/04/04頃からThreadsとの接続ができるようになったようで、Threadsのアカウントが検索・フォローできるようになり、threads.netのドメインタイムラインも表示されています。

ただし、クローズするかどうかはしばらく様子見します。

**Comment by hanubeki** [comment]
Threadsと接続できるようになって1週間経ちましたが、問題なさそうなのでクローズします。

**Comment by hanubeki** [comment]
2024/10/05頃からまたThreadsとの接続ができなくなっているのでReopenします

**Comment by noellabo** [comment]
当初は、障害により2〜3時間fedibird.comの/publicに接続しにくくなったことによる判断と考えていましたが、障害の発生していなかったnightly.fedibird.comもブロック対象となっていることから、公開されているフィードとみなす判断基準の変更があった可能性があります。

**Comment by hanubeki** [comment]
2024/10/18頃から再びThreadsとの接続ができるようになりましたが、クローズは1週間様子見します

**Comment by hanubeki** [comment]
1週間を過ぎてしまいましたが、問題なさそうなのでクローズします。
