### ISSUE TITLE
サークルについて

### ISSUE THREAD

**Issue by blank71** [fedibird/mastodon#5]
- サークルを使った投稿がリストタイムラインで表示されません。

- サークルを使った投稿で対象としている人を確認できません。

サークルを使って投稿したときに投稿者は投稿単位で誰を対象に投稿したか確認できます。投稿者がその投稿に対してリプライしたものは自分で再び対象を設定しない限りリプライ元の設定した対象が引き継がれるものの、誰を対象にしたのか確認することができません。詳しいことは分からないので申し訳ないですが、内部的には再設定しない限りリプライ元の対象が引き継がれていきますが、UI 上で確認することができないみたいです。

**Comment by noellabo** [comment]
現在、リストタイムラインへは配送しないようになっています。
望ましい挙動を検討しますので、少々お待ちください。

> サークルを使った投稿で対象としている人を確認できません。

サークルの投稿に返信する際、誰に届くか分からない（秘匿されている）のは仕様です。
サークルのメンバー（宛先）を知ることができるのは、サークルの所有者、つまり元の投稿者だけです。

秘密の宛先に送る機能だと思ってください。

（現在のサークルにリプライ）で返信する場合、誰に送って良いかわからないので、親投稿を行ったサーバへ転送します。
親投稿を行ったサーバは、転送されてきたリプライをサークルの宛先にリレーします。

**Comment by blank71** [comment]
親投稿とリプライである子投稿の投稿者が同じである場合、当たり前ですが親投稿の投稿者は親投稿の宛先を確認することができますが、子投稿の宛先は確認できないようになっています。個人的には、この状態においてこの子投稿の宛先を確認できたらよいな、と感じます。ですが、親投稿を確認すればよいだけなので、現状のままでもよいと思います。

**Comment by noellabo** [comment]
宛先を一覧する機能はデバッグに便利ですが、利用者が投稿後に意識を向けるべきものではないので、本番環境では無くした方が良いのかもしれません。
