### ISSUE TITLE
quoteURL --> quoteUrl

### ISSUE THREAD

**Issue by alexgleason** [fedibird/mastodon#9]
### Expected behaviour

The Note has a property named quoteURL

### Actual behaviour

It should be named quoteUrl

### Steps to reproduce the problem

```
curl -H "Accept: application/activity+json" https://fedibird.com/@noellabo/107663670404015196
```

It says: `"quoteURL": "https://misskey.io/notes/8vsn2izjwh"`

Should be: `"quoteUrl": "https://misskey.io/notes/8vsn2izjwh"`

### Specifications

main

**Comment by noellabo** [comment]
Thanks, Alex.

The improper conversion was due to an Acronym definition by Mastodon in Rails.
Falling back to `_misskey_quote` seemed to do the trick.

However, it seems more appropriate to use URIs rather than URLs in the first place.
So I'll fix it to `quoteUri`.

**Comment by alexgleason** [comment]
I agree `quoteUri` is a better name. We are now sending `quoteUri` so federation is restored. :+1:
